# Generated by Django 2.2.4 on 2019-08-07 16:29

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('summary', models.CharField(max_length=400)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='#')),
                ('detail', models.TextField()),
            ],
        ),
    ]
