# Generated by Django 2.2.4 on 2019-08-09 09:11

import django.core.validators
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photographer', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('summary', models.CharField(max_length=400)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/product')),
                ('detail', models.TextField()),
                ('options', models.CharField(max_length=500)),
                ('option_price', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10000000), django.core.validators.MinValueValidator(0)])),
                ('location', models.CharField(max_length=300)),
            ],
        ),
    ]
