# Generated by Django 2.1.7 on 2019-08-21 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photographer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productregistration',
            options={'ordering': ['-id']},
        ),
    ]
